#ifndef QTPLATFORMTHEMEGLOBAL_H
#define QTPLATFORMTHEMEGLOBAL_H

#include <QtCore/QtGlobal>

#if defined (QT_PLATFORM_THEME_LIBRARY)
#define QT_PLATFORM_THEME_SHARED_EXPORT     Q_DECL_EXPORT
#else
#define QT_PLATFORM_THEME_SHARED_EXPORT     Q_DECL_IMPORT
#endif

#endif // QTPLATFORMTHEMEGLOBAL_H
